//CATEGORIES TYPES
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';

//PRODUCTS TYPES
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const FILTER_PRODUCTS_BY_SUBLEVEL = 'FILTER_PRODUCTS_BY_SUBLEVEL';

//CART TYPES
export const ADD_ITEM_CART = 'ADD_ITEM_CART';
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';
export const EDIT_ITEM_CART = 'EDIT_ITEM_CART';
