//CATEGORIES TYPES
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';


//PRODUCTS TYPES
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const FILTER_PRODUCTS_BY_SUBLEVEL = 'FILTER_PRODUCTS_BY_SUBLEVEL';
